### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by dsm-72** [KrishnaswamyLab/PHATE#135]
**Is your feature request related to a problem? Please describe.**
Here is an example yaml file. Everything up to `phate==1.0.10` installs without conflicts. Adding phate causes the environment to fail due to conflicts. Relaxing the version restrictions on phate (to see which, if any, version is compatible) yields `0.4.5`. This is likely due to a requirements issue in the `setup.py` file. 

```yml
name: test_env
channels:
  - pytorch
  - conda-forge  
  - fastai  
  - bioconda
  # - nvidia  
 
dependencies:  
  - python>=3.10.9

  # Utilities
  - tqdm

  # Jupyter Notebook
  - conda-forge::notebook==6.5.3 
  - conda-forge::ipykernel==6.22.0
  - conda-forge::ipywidgets==8.0.4
  - conda-forge::jupyter_contrib_nbextensions==0.7.0
  
  # nbdev
  - fastai::nbdev==2.3.12

  # PyTorch
  - pytorch==2.0.0  
  - conda-forge::pytorch-lightning==2.0.0
  - conda-forge::torchdiffeq==0.2.2

  # Plotting
  - conda-forge::matplotlib=3.7.1
  - conda-forge::seaborn==0.12.2   
  
  # Data
  - conda-forge::scikit-learn=1.2.1
  - pandas==1.5.3
  - numpy==1.23.5
  - scipy

  # Single-Cell
  - conda-forge::scanpy==1.9.2
  - conda-forge::anndata==0.8.0
  
  # Krishnaswamy Lab
  - graphtools  
  - bioconda::scprep==1.2.2
  - bioconda::phate==0.4.5
  # - bioconda::phate==1.0.10
  

  # Pip / non-conda packages
  - pip
  - pip: 
    # PyTorch   
    - pot
    - torchdyn==1.0.3
    
    # Krishnaswamy Lab
    - magic-impute

```

**Describe the solution you'd like**
Release a major version of phate (`>=1.X.X`) compatible with the above environment

**Comment by scottgigante** [comment]
Can you make a miminum working example? You'll need to figure out which of your dependencies is the culprit by eliminating them one by one, and then provide a single command `conda install ...` that replicates the issue.

**Comment by dsm-72** [comment]
@scottgigante 

Above is the MWE.`conda create env -f env.yml` and then as you said, removed packages one by one until I no longer had the error.... except:

- Strangely  this affects M1 and M2 Macs not Linux (Ubuntu 20+) or Windows systems. I could use the above file with 1.0.10 on Ubuntu 20.04TLS.


- The issue is literally on the python version 😭 
```yml
name: test_env_2
channels:
  - pytorch
  - conda-forge  
  - fastai  
  - bioconda
  - dglteam
  # - nvidia  
 
dependencies:  
  - python>=3.10                        # <----------- here 3.10.9 --> 3.10

  # Utilities
  # - tqdm

  # Jupyter Notebook
  # - conda-forge::notebook==6.5.3 
  # - conda-forge::ipykernel==6.22.0
  # - conda-forge::ipywidgets==8.0.4
  # - conda-forge::jupyter_contrib_nbextensions==0.7.0
  
  # nbdev
  # - fastai::nbdev==2.3.12

  # PyTorch
  # - pytorch==2.0.0  
  # - conda-forge::pytorch-lightning==2.0.0
  # - conda-forge::torchdiffeq==0.2.2
  # - dglteam::dgl==1.0.1

  # Plotting
  # - conda-forge::matplotlib=3.7.1
  # - conda-forge::seaborn==0.12.2   
  
  # Data
  # - conda-forge::scikit-learn=1.2.1
  # - pandas==1.5.3
  # - numpy==1.23.5
  # - scipy

  # Single-Cell
  # - conda-forge::scanpy==1.9.2
  # - conda-forge::anndata==0.8.0
  
  # Krishnaswamy Lab
  # - graphtools  
  # - bioconda::scprep==1.2.2
  # - bioconda::phate==0.4.5
  - bioconda::phate==1.0.10
  

  # # Pip / non-conda packages
  # - pip
  # - pip: 
  #   # PyTorch   
  #   - pot
  #   - torchdyn==1.0.3

  #   # Krishnaswamy Lab
  #   - magic-impute


```

and here we see

```sh
conda env create -f test_env2.yml
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                     
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
bioconda::phate==1.0.10 -> python[version='>=3.5']
bioconda::phate==1.0.10 -> deprecated -> python[version='>=2.7|>=3.8|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0|>=3.10,<3.11.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0|>=3.11,<3.12.0a0|>=3.11,<3.12.0a0|>=3.6',build=*_cpython]
python[version='>=3.10']

```
